### ISSUE TITLE
Missing tower data file should be error or option

### ISSUE THREAD

**Issue by mswart** [jgraichen/salt-tower#1]
salt-tower logs a warning for every missing tower data file. This is noisy due to missing data file based on generic matches like ```arch/{{ pillar['arch'].sls``` or `minion/{{ grains['id'] }}.sls`.

It should be possible to mark includes as optional (so no warning is logged). Missing required data files should result in a noticeable error.

**Comment by jgraichen** [comment]
This feature has been implemented in [1.9.0](https://github.com/jgraichen/salt-tower/releases/tag/v1.9.0).
