### ISSUE TITLE
tower.sls rendering ignores env 

### ISSUE THREAD

**Issue by zixo** [jgraichen/salt-tower#41]
**tower.sls env ignored**

I am not able to use salt-tower with multiple environments.

**To Reproduce**

salt-master configuration

/etc/salt/master.d/f_defaults.conf:
<pre>
...
gitfs_remotes:
  - https://github.com/jgraichen/salt-tower.git:
    - all_saltenvs: v1.10.0
ext_pillar:
  - tower: /srv/salt/towers/tower.sls
...
</pre>

salt-minion configuration

<pre>
$ salt salt-master config.get salt:minion
salt-master:
    ----------
    http_connect_timeout:
        60
    lock_saltenv:
        True
    pillarenv:
        saltmaster
    saltenv:
        saltmaster
    state_top_saltenv:
        saltmaster
</pre>

Tower .sls

/srv/salt/towers/tower.sls
<pre>
saltmaster:
  - '*':
    - magic: saltmaster_8ed104d8-dced-4d73-8816-0da95e74ab21
</pre>

Output
<pre>
$ salt salt-master pillar.get magic -ldebug
...
[DEBUG   ] Rendered data from file: /srv/salt/towers/tower.sls:
...
saltmaster:
  - '*':
    - magic: saltmaster_8ed104d8-dced-4d73-8816-0da95e74ab21
...
salt-master:
</pre>

I get pillar corectly render only if I use `base`.

**Expected behavior**
Access pillar data per env.

**Environment information:**
 - Salt version: [3004.2]
 - Python version [3.7.15]
 - Operating system [Amazon Linux 2]

**Comment by jgraichen** [comment]
Release with v1.12.0.
